name: Publish VSCode Extension

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Lint and build
      run: npm run pretest

    - name: Compile extension
      run: npm run package

    - name: Install vsce
      run: npm install -g @vscode/vsce

    - name: Publish extension
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: vsce publish
